layout_spectrum: 0.3075708766223512
typography_spectrum: 0.6944607530546254
color:
  brandStrength: 0.25685156560226313
  lightness: 0.8547574466011385
  saturation: 0.6367150143509971
  rhythmicContrast: 0.24072281238954918
  brandColors:
    - '#2E0927'
    - '#D90000'
    - '#FF2D00'
    - '#FF8C00'
    - '#04756F'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: Vegas Personal Injury Experts
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FyCFviH3ZH04%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DyCFviH3ZH04&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FyCFviH3ZH04%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Cap & Kudler
          url: 'https://www.youtube.com/user/LasVegasLawyersNV'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://www.youtube.com/favicon.ico'
        domain: youtu.be
      keywords: []
      description: Our logo animated
      '@type': VideoObject
      app_links: []
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://youtu.be/yCFviH3ZH04'
      title: Animated Logo
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
title: ''
description: ''
purpose:
  - type: contact
    url: 'tel:7028788778'
    label: Call Now
  - type: contact
    url: 'mailto:management@capandkudler.com'
    label: Contact Us
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0694d57d-7317-4bae-a286-abc7909b9fe5.png
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/758f681d-2645-4606-9c37-17ae8027fff9.gif
author:
  name: Cap & Kudler
  email: info@capandkudler.com
  url: 'http://www.capandkudler.com'
url: 'http://www.personalinjuryexperts.vegas'
github: true
